target("PartyQuestSkseLineageBridge")
    set_basename("SkyrimTogetherLineageBridge")
    set_kind("shared")
    set_group("Client")
    add_includedirs("../encoding")
    add_files("PartyQuestSkseLineageBridge.cpp")
    add_syslinks("bcrypt")
